var gzys = {
  // 视频
  'mp4': 'video',
  'avi': 'video',
  '3gp': 'video',
  'rmvb': 'video',
  'rm': 'video',
  'wmv': 'video',
  'mkv': 'video',
  'mpeg': 'video',
  'mpg': 'video',
  'vob': 'video',
  'mov': 'video',
  'swf': 'video',
  'flv': 'video',
  'f4v': 'video',
  'dat': 'video',
  'VCD': 'video',
  'drc': 'video',
  'dsm': 'video',
  'dsv': 'video',
  'dsa': 'video',
  'dss': 'video',
  'ifo': 'video',
  'd2v': 'video',
  'fli': 'video',
  'flc': 'video',
  'lic': 'video',
  'ivf': 'video',
  'mpe': 'video',
  'mtv': 'video',
  'm1v': 'video',
  'm2v': 'video',
  'mpv2': 'video',
  'mp2v': 'video',
  'ts': 'video',
  'tp': 'video',
  'tpr': 'video',
  'pva': 'video',
  'pss': 'video',
  'm4v': 'video',
  'm4p': 'video',
  'm4b': 'video',
  '3gpp': 'video',
  '3g2': 'video',
  '3gp2': 'video',
  'ogm': 'video',
  'qt': 'video',
  'amr': 'video',
  'ratdvd': 'video',
  'rt': 'video',
  'rp': 'video',
  'smi': 'video',
  'smil': 'video',
  'amv': 'video',
  'dmv': 'video',
  'navi': 'video',
  'ra': 'video',
  'ram': 'video',
  'rpm': 'video',
  'roq': 'video',
  'smk': 'video',
  'bik': 'video',
  'wmp': 'video',
  'wm': 'video',
  'asf': 'video',
  'asx': 'video',
  'm3u': 'video',
  'pls': 'video',
  'wvx': 'video',
  'wax': 'video',
  'wmx': 'video',
  'mpcpl': 'video',
  'mpeg4': 'video',
  'mpg4': 'video',
  'mpeg1': 'video',
  'mpg1': 'video',
  'mpeg2': 'video',
  'mpg2': 'video',
  // 音乐
  'mp3': 'music',
  'MP3': 'music',
  'wma': 'music',
  'flac': 'music',
  'aac': 'music',
  'mmf': 'music',
  'm4a': 'music',
  'm4r': 'music',
  'Ogg': 'music',
  'wav': 'music',
  'wavpack': 'music',
  'wave': 'music',
  'au': 'music',
  'CD': 'music',
  'ogg': 'music',
  'mpc': 'music',
  'ape': 'music',
  'ac3': 'music',
  'mpa': 'music',
  'mp2': 'music',
  'm1a': 'music',
  'm2a': 'music',
  'mid': 'music',
  'midi': 'music',
  'rmi': 'music',
  'mka': 'music',
  'dts': 'music',
  'cda': 'music',
  'snd': 'music',
  'aif': 'music',
  'aifc': 'music',
  'aiff': 'music',
  'ofr': 'music',
  'realAudio': 'music',
  'vqf': 'music',
  // word
  'doc': 'word',
  'docx': 'word',
  'txt': 'word',
  'pdf': 'word',
  // excle
  'xls': 'excle',
  'xlsx': 'excle',
  // ppt
  'ppt': 'ppt',
  'pptx': 'ppt',
  'pps': 'ppt',
  'ppsx': 'ppt',
  // 压缩文件
  'rar': 'compressed',
  'zip': 'compressed',
  'tar': 'compressed',
  'cab': 'compressed',
  'uue': 'compressed',
  'jar': 'compressed',
  'iso': 'compressed',
  'z': 'compressed',
  '7-zip': 'compressed',
  'ace': 'compressed',
  'lzh': 'compressed',
  'arj': 'compressed',
  'gzip': 'compressed',
  'bz2': 'compressed',
  // img
  'bmp': 'img',
  'gif': 'img',
  'jpeg': 'img',
  'trff': 'img',
  'png': 'img',
  'PNG': 'img',
  'svg': 'img',
  'pcx': 'img',
  'dxf': 'img',
  'wmf': 'img',
  'emf': 'img',
  'jpg': 'img',
  'JPG': 'img',
  'tga': 'img'
}
var typeClass = {
  'img': '#icon-moren',
  'compressed': '#icon-zip',
  'ppt': '#icon-ppt',
  'excle': '#icon-xls',
  'word': '#icon-word',
  'music': '#icon-yinle',
  'video': '#icon-video'
  // #icon-qita
}
export function getFileType(fileName) {
  const numLast = fileName.split(/[.]/).length - 1
  const format = fileName.split(/[.]/)[numLast]
  return gzys[format] || 'other'
}

export function getFileIcon(fileName) {
  // const numLast = fileName.split('.').length - 1
  // const format = fileName.split('.')[numLast]

  var index1 = fileName.lastIndexOf('.')

  var index2 = fileName.length

  var suffix = fileName.substring(index1 + 1, index2)// 后缀名

  var type = gzys[suffix]
  var Ttype = typeClass[type]

  return Ttype || '#icon-qita'
}
